name: muscyou
description: "Yet another everyday workouts tracker."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.21.2
  go_router: ^15.0.0
  hooks_riverpod: ^3.0.3
  sqflite: ^2.4.2
  path: ^1.8.0
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  generate: true
